### ISSUE TITLE
:sparkles: Run as AnyUser.

### ISSUE THREAD

**Issue by jortel** [konveyor/tackle2-addon-discovery#6]
We need to make the same change in go.mod and the Docker file as addon-analyzer.

The failed container below may be related.
```
    image: quay.io/konveyor/tackle2-addon-discovery:latest
    imageID: docker-pullable://quay.io/konveyor/tackle2-addon-discovery@sha256:a9e27a282e4a8f3e7e43f6ae7e9a71a04eb2e81fd0731c2198f7d116ecc5ae04
    lastState: {}
    name: addon
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://de6bd235a54d8ad13622e51a43a86b99c4110fb031d9718d2f9c44792995027b
        exitCode: 128
        finishedAt: "2024-10-16T13:55:56Z"
        message: 'unable to find user default: no matching entries in passwd file'
        reason: ContainerCannotRun
        startedAt: "2024-10-16T13:55:56Z"
```

ref: https://github.com/konveyor/tackle2-addon-analyzer/pull/133
